[build]
  command = "npm install && npm run minify" 
  publish = "." 

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[system]
  # Specify a modern Node.js version for Netlify to use
  node_version = "20"